version: "3.9"
services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432"


  app:
    build: "."
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      db_host: postgres
    volumes:
      - ./logs:/telegram_bot/logs

  redis:
    image: redis
    ports:
      - "6379"
    depends_on:
      - app
