"""add role admin and verify_token to admin

Revision ID: 00e5fbae5d37
Revises: 113a9d82bbe0
Create Date: 2023-06-20 20:03:59.204874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00e5fbae5d37'
down_revision = '113a9d82bbe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verify_token', sa.String(), nullable=True))
    op.drop_column('users', 'roles')
    op.add_column('Сессии пользователей', sa.Column('expire_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Сессии пользователей', 'expire_date')
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'verify_token')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
